//! IDT: 48 vectors (0..31 exceptions, 32 timer, 33 keyboard, 44 mouse) plus
//! the int 0x80 system call gate. Stubs live in `asm.rs` (global_asm).

use core::arch::asm;
use core::cell::UnsafeCell;

/// Full CPU state at interrupt entry, pushed by `isr_common`.
/// Stack order at hand-off: r15 lowest ... rax, vector, err, rip, cs,
/// rflags, rsp, ss (user rsp/ss present only from user mode).
#[repr(C)]
#[derive(Clone, Copy)]
pub struct IrqFrame {
    pub r15: u64,
    pub r14: u64,
    pub r13: u64,
    pub r12: u64,
    pub r11: u64,
    pub r10: u64,
    pub r9: u64,
    pub r8: u64,
    pub rbp: u64,
    pub rdi: u64,
    pub rsi: u64,
    pub rdx: u64,
    pub rcx: u64,
    pub rbx: u64,
    pub rax: u64,
    pub vector: u64,
    pub err: u64,
    pub rip: u64,
    pub cs: u64,
    pub rflags: u64,
    pub rsp: u64,
    pub ss: u64,
}

const IDT_ENTRIES: usize = 129;

#[repr(C, packed)]
#[derive(Clone, Copy)]
struct IdtEntry {
    off_low: u16,
    sel: u16,
    ist: u8,
    flags: u8,
    off_mid: u16,
    off_high: u32,
    zero: u32,
}

struct IdtCell(UnsafeCell<[IdtEntry; IDT_ENTRIES]>);
unsafe impl Sync for IdtCell {}

static IDT: IdtCell = IdtCell(UnsafeCell::new(
    [IdtEntry {
        off_low: 0,
        sel: 0,
        ist: 0,
        flags: 0,
        off_mid: 0,
        off_high: 0,
        zero: 0,
    }; IDT_ENTRIES],
));

#[repr(C, packed)]
struct Idtr {
    limit: u16,
    base: u64,
}

const KERNEL_CS_SEL: u16 = 0x08;
const GATE_INT: u8 = 0x8E; // present, DPL0, 64-bit interrupt gate

fn idt_set(n: usize, handler: usize, flags: u8) {
    let addr = handler as u64;
    unsafe {
        (*IDT.0.get())[n] = IdtEntry {
            off_low: (addr & 0xFFFF) as u16,
            sel: KERNEL_CS_SEL,
            ist: 0,
            flags,
            off_mid: ((addr >> 16) & 0xFFFF) as u16,
            off_high: (addr >> 32) as u32,
            zero: 0,
        };
    }
}

extern "C" {
    /// One entry per vector 0..=47, generated by global_asm in asm.rs.
    static isr_stub_table: [usize; 48];
    fn isr_stub_128();
}

const IRQ_TIMER: u64 = 32;
const IRQ_KEYBOARD: u64 = 33;
const IRQ_MOUSE: u64 = 44;

const EXC_NAMES: [&str; 32] = [
    "#DE divide error",
    "#DB debug",
    "NMI",
    "#BP breakpoint",
    "#OF overflow",
    "#BR bound range",
    "#UD invalid opcode",
    "#NM device not avail",
    "#DF double fault",
    "coproc segment overrun",
    "#TS invalid TSS",
    "#NP segment absent",
    "#SS stack fault",
    "#GP general protection",
    "#PF page fault",
    "reserved",
    "#MF x87 FP error",
    "#AC alignment check",
    "#MC machine check",
    "#XM SIMD FP error",
    "#VE virtualization",
    "#CP control protection",
    "reserved",
    "reserved",
    "reserved",
    "reserved",
    "reserved",
    "reserved",
    "#HV hypervisor",
    "#VC VMM comm",
    "#SX security",
    "reserved",
];

pub static mut TIMER_TICKS: u64 = 0;
/// Flipped once the scheduler is initialised.
pub static mut SCHED_ENABLED: bool = false;

fn on_timer(f: &mut IrqFrame) {
    unsafe {
        TIMER_TICKS += 1;
        if TIMER_TICKS % 100 == 0 {
            crate::klog_info!(
                "timer: {} ticks (~{}s)",
                TIMER_TICKS,
                TIMER_TICKS / 100
            );
        }
        if SCHED_ENABLED {
            crate::sched::sched_tick(f);
        }
    }
}

pub fn timer_ticks() -> u64 {
    unsafe { TIMER_TICKS }
}

fn on_keyboard() {
    let sc = crate::io::inb(0x60);
    crate::kbd::kbd_on_scancode(sc);
}

#[no_mangle]
extern "C" fn isr_handler(f: &mut IrqFrame) {
    if f.vector == 0x80 {
        crate::syscall::syscall_dispatch(f);
        return;
    }

    if f.vector >= 32 {
        match f.vector {
            IRQ_TIMER => {
                on_timer(f);
                crate::pic::eoi(0);
            }
            IRQ_KEYBOARD => {
                on_keyboard();
                crate::pic::eoi(1);
            }
            IRQ_MOUSE => {
                crate::gui::mouse::irq_handler();
                crate::pic::eoi(12);
            }
            v => {
                crate::klog_warn!("irq: stray vector {}", v);
                crate::pic::eoi((v - 32) as u8);
            }
        }
        return;
    }

    if f.vector == 3 {
        // #BP: recoverable test exception, just return
        crate::klog_info!("int3: handled at rip={:#x} (resuming)", f.rip);
        return;
    }

    crate::klog_err!(
        "EXCEPTION {}: {} err={:#x}",
        f.vector,
        EXC_NAMES[f.vector as usize],
        f.err
    );
    if f.vector == 14 {
        let cr2: u64;
        unsafe { asm!("mov {}, cr2", out(reg) cr2, options(nomem, nostack, preserves_flags)) };
        crate::klog!("  cr2={:#x}\n", cr2);
    }
    crate::klog!(
        "  rip={:#x} cs={:#x} rflags={:#x} rsp={:#x}\n",
        f.rip,
        f.cs,
        f.rflags,
        f.rsp
    );
    crate::klog!(
        "  rax={:#x} rbx={:#x} rcx={:#x} rdx={:#x}\n",
        f.rax,
        f.rbx,
        f.rcx,
        f.rdx
    );
    crate::klog!("  rsi={:#x} rdi={:#x} rbp={:#x}\n", f.rsi, f.rdi, f.rbp);

    crate::io::cli();
    loop {
        crate::io::hlt();
    }
}

pub fn init() {
    unsafe {
        for i in 0..48usize {
            idt_set(i, isr_stub_table[i], GATE_INT);
        }
    }

    idt_set(0x80, isr_stub_128 as usize, 0xEE); // present, DPL=3, interrupt gate

    let idtr = Idtr {
        limit: (core::mem::size_of::<[IdtEntry; IDT_ENTRIES]>() - 1) as u16,
        base: unsafe { (*IDT.0.get()).as_ptr() as u64 },
    };
    unsafe {
        asm!("lidt [{}]", in(reg) &idtr, options(nostack));
    }

    crate::pic::init();
    crate::pic::unmask(0); // PIT timer
    crate::pic::unmask(1); // keyboard

    crate::klog_info!(
        "idt: {} vectors loaded, PIC remapped, IRQ0/IRQ1 unmasked",
        IDT_ENTRIES
    );
}

pub fn enable() {
    crate::io::sti();
    crate::klog_info!(
        "interrupts enabled (ticks so far: {})",
        timer_ticks()
    );
}
