/* IDT for 48 vectors: 0..31 CPU exceptions, 32 timer (IRQ0), 33 keyboard
 * (IRQ1), 34..47 reserved-but-installed with default stubs.
 * Stubs are generated macro-by-macro in isr.S.
 */
#include "idt.h"
#include "pic.h"
#include "kprintf.h"

#define IDT_ENTRIES 129   /* 0..47 exceptions/IRQs, 0x80 syscall */

struct idt_entry {
    uint16_t off_low;
    uint16_t sel;
    uint8_t  ist;
    uint8_t  flags;
    uint16_t off_mid;
    uint32_t off_high;
    uint32_t zero;
} __attribute__((packed));

static struct idt_entry idt[IDT_ENTRIES];

struct idtr {
    uint16_t limit;
    uint64_t base;
} __attribute__((packed));

#define KERNEL_CS_SEL 0x08
#define GATE_INT      0x8E   /* present, DPL0, 64-bit interrupt gate */

static void idt_set(uint8_t n, void (*handler)(void)) {
    uint64_t addr = (uint64_t)handler;
    idt[n] = (struct idt_entry){
        .off_low  = (uint16_t)(addr & 0xFFFF),
        .sel      = KERNEL_CS_SEL,
        .ist      = 0,
        .flags    = GATE_INT,
        .off_mid  = (uint16_t)((addr >> 16) & 0xFFFF),
        .off_high = (uint32_t)(addr >> 32),
        .zero     = 0,
    };
}

/* --- stub table: one entry per vector, generated by isr.S ----------------- */

#define DECL_STUB(n) extern void isr_stub_##n(void);
#define STUB(n)      isr_stub_##n,

#define FOR_0_47(X) \
    X(0)  X(1)  X(2)  X(3)  X(4)  X(5)  X(6)  X(7)  \
    X(8)  X(9)  X(10) X(11) X(12) X(13) X(14) X(15) \
    X(16) X(17) X(18) X(19) X(20) X(21) X(22) X(23) \
    X(24) X(25) X(26) X(27) X(28) X(29) X(30) X(31) \
    X(32) X(33) X(34) X(35) X(36) X(37) X(38) X(39) \
    X(40) X(41) X(42) X(43) X(44) X(45) X(46) X(47)

FOR_0_47(DECL_STUB)

static void (*const stub_table[IDT_ENTRIES])(void) = { FOR_0_47(STUB) };

extern void isr_stub_128(void);            /* int 0x80 system calls */
extern void syscall_dispatch(struct irq_frame *f);

/* --- C handler ------------------------------------------------------------ */

#define IRQ_TIMER    32
#define IRQ_KEYBOARD 33
#define IRQ_MOUSE    44

static const char *const exc_names[32] = {
    "#DE divide error",        "#DB debug",             "NMI",
    "#BP breakpoint",          "#OF overflow",          "#BR bound range",
    "#UD invalid opcode",      "#NM device not avail",  "#DF double fault",
    "coproc segment overrun",  "#TS invalid TSS",       "#NP segment absent",
    "#SS stack fault",         "#GP general protection","#PF page fault",
    "reserved",                "#MF x87 FP error",      "#AC alignment check",
    "#MC machine check",       "#XM SIMD FP error",     "#VE virtualization",
    "#CP control protection",  "reserved",              "reserved",
    "reserved",                "reserved",              "reserved",
    "reserved",                "#HV hypervisor",        "#VC VMM comm",
    "#SX security",            "reserved",
};

volatile uint64_t timer_ticks;
int sched_enabled;                     /* flipped by sched_init()'s owner */

static void on_timer(struct irq_frame *f) {
    timer_ticks++;
    if (timer_ticks % 100 == 0)
        KLOG_INFO("timer: %lu ticks (~%lus)", timer_ticks, timer_ticks / 100);

    extern int  sched_enabled;
    if (sched_enabled) {
        extern void sched_tick(struct irq_frame *f);
        sched_tick(f);
    }
}

static void on_keyboard(void) {
    uint8_t sc;
    __asm__ volatile ("inb $0x60, %0" : "=a"(sc));
    extern void kbd_on_scancode(uint8_t);
    kbd_on_scancode(sc);
}

void isr_handler(struct irq_frame *f) {
    if (f->vector == 0x80) { syscall_dispatch(f); return; }

    if (f->vector >= 32) {
        switch (f->vector) {
        case IRQ_TIMER:    on_timer(f);    pic_eoi(0);            return;
        case IRQ_KEYBOARD: on_keyboard(); pic_eoi(1);            return;
        case IRQ_MOUSE: {
            extern void mouse_irq_handler(void);
            mouse_irq_handler();
            pic_eoi(12);
            return;
        }
        default:           KLOG_WARN("irq: stray vector %lu", f->vector);
                           pic_eoi((uint8_t)(f->vector - 32));   return;
        }
    }

    if (f->vector == 3) {  /* #BP: recoverable test exception, just return */
        KLOG_INFO("int3: handled at rip=%p (resuming)", (void *)f->rip);
        return;
    }

    KLOG_ERR("EXCEPTION %lu: %s err=%#lx", f->vector,
             exc_names[f->vector], f->err);
    if (f->vector == 14) {
        uint64_t cr2;
        __asm__ volatile ("mov %%cr2, %0" : "=r"(cr2));
        kprintf("  cr2=%p\n", (void *)cr2);
    }
    kprintf("  rip=%p cs=%#lx rflags=%#lx rsp=%p\n",
            (void *)f->rip, f->cs, f->rflags, (void *)f->rsp);
    kprintf("  rax=%#lx rbx=%#lx rcx=%#lx rdx=%#lx\n",
            f->rax, f->rbx, f->rcx, f->rdx);
    kprintf("  rsi=%#lx rdi=%#lx rbp=%#lx\n", f->rsi, f->rdi, f->rbp);

    __asm__ volatile ("cli");
    for (;;)
        __asm__ volatile ("hlt");
}

/* --- init ------------------------------------------------------------------ */

void idt_init(void) {
    for (int i = 0; i < 48; i++)
        idt_set((uint8_t)i, stub_table[i]);

    idt_set(0x80, isr_stub_128);
    idt[0x80].flags = 0xEE;   /* present, DPL=3, interrupt gate */

    struct idtr idtr = {
        .limit = sizeof(idt) - 1,
        .base  = (uint64_t)&idt,
    };
    __asm__ volatile ("lidt %0" : : "m"(idtr));

    pic_init();
    pic_unmask(0);   /* PIT timer */
    pic_unmask(1);   /* keyboard */

    KLOG_INFO("idt: %d vectors loaded, PIC remapped, IRQ0/IRQ1 unmasked",
              IDT_ENTRIES);
}

void idt_enable(void) {
    __asm__ volatile ("sti");
    KLOG_INFO("interrupts enabled");
}
